CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) UNIQUE NOT NULL,
                       password VARCHAR(255) NOT NULL
);

CREATE TABLE books (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL DEFAULT 'Untitled',
                       author VARCHAR(255) NOT NULL DEFAULT 'Unknown',
                       file_path VARCHAR(255) NOT NULL,
                       cover_image_path VARCHAR(255),
                       is_default BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_books_is_default ON books(is_default);

CREATE TABLE chapters (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          title VARCHAR(255) NOT NULL DEFAULT 'Untitled Chapter',
                          chapter_index INTEGER NOT NULL,
                          file_path VARCHAR(255) NOT NULL,
                          anchor VARCHAR(255),
                          book_id BIGINT NOT NULL,
                          CONSTRAINT fk_chapters_book FOREIGN KEY (book_id)
                              REFERENCES books(id) ON DELETE CASCADE
);

-- Composite index for efficient chapter retrieval by book and chapter order
CREATE INDEX idx_chapters_book_chapter ON chapters(book_id, chapter_index);

CREATE TABLE user_books (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id BIGINT NOT NULL,
                            book_id BIGINT NOT NULL,
                            last_chapter_index INTEGER NOT NULL DEFAULT 0,
                            CONSTRAINT fk_user_books_user FOREIGN KEY (user_id)
                                REFERENCES users(id) ON DELETE CASCADE,
                            CONSTRAINT fk_user_books_book FOREIGN KEY (book_id)
                                REFERENCES books(id) ON DELETE CASCADE
);