ALTER TABLE users
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE books
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE user_books
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN last_accessed TIMESTAMP;

ALTER TABLE chapters
    ADD COLUMN word_count INTEGER NOT NULL DEFAULT 0;