CREATE TABLE book_files (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            file_path VARCHAR(255) NOT NULL,
                            file_format VARCHAR(50) NOT NULL,
                            file_size BIGINT NOT NULL,
                            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                            book_id BIGINT UNIQUE NOT NULL,
                            CONSTRAINT fk_book_files_book FOREIGN KEY (book_id)
                                REFERENCES books(id) ON DELETE CASCADE
);

CREATE TABLE book_images (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             file_path VARCHAR(255) NOT NULL,
                             media_type VARCHAR(100) NOT NULL,
                             file_size BIGINT NOT NULL,
                             image_type VARCHAR(50) NOT NULL,
                             width INTEGER,
                             height INTEGER,
                             created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                             book_id BIGINT NOT NULL,
                             CONSTRAINT fk_book_images_book FOREIGN KEY (book_id)
                                 REFERENCES books(id) ON DELETE CASCADE
);

CREATE INDEX idx_book_images_book_type ON book_images(book_id, image_type);
CREATE UNIQUE INDEX idx_book_images_cover ON book_images(book_id) WHERE image_type = 'COVER';

ALTER TABLE books DROP COLUMN file_path;
ALTER TABLE books DROP COLUMN cover_image_path;