CREATE TABLE default_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT UNIQUE NOT NULL,
    CONSTRAINT fk_default_books_book FOREIGN KEY (book_id)
        REFERENCES books(id) ON DELETE CASCADE
);

INSERT INTO default_books (book_id)
SELECT id FROM books WHERE is_default = true;

ALTER TABLE books DROP COLUMN is_default;