/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as Import3RouteImport } from './routes/import3'
import { Route as Import2RouteImport } from './routes/import2'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReaderBookIdRouteImport } from './routes/reader/$bookId'
import { Route as ApiImportRetryRouteImport } from './routes/api/import-retry'
import { Route as ApiImportRouteImport } from './routes/api/import'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const Import3Route = Import3RouteImport.update({
  id: '/import3',
  path: '/import3',
  getParentRoute: () => rootRouteImport,
} as any)
const Import2Route = Import2RouteImport.update({
  id: '/import2',
  path: '/import2',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderBookIdRoute = ReaderBookIdRouteImport.update({
  id: '/reader/$bookId',
  path: '/reader/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRetryRoute = ApiImportRetryRouteImport.update({
  id: '/api/import-retry',
  path: '/api/import-retry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRoute = ApiImportRouteImport.update({
  id: '/api/import',
  path: '/api/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/import2': typeof Import2Route
  '/import3': typeof Import3Route
  '/library': typeof LibraryRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/import': typeof ApiImportRoute
  '/api/import-retry': typeof ApiImportRetryRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/import2': typeof Import2Route
  '/import3': typeof Import3Route
  '/library': typeof LibraryRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/import': typeof ApiImportRoute
  '/api/import-retry': typeof ApiImportRetryRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/import2': typeof Import2Route
  '/import3': typeof Import3Route
  '/library': typeof LibraryRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/import': typeof ApiImportRoute
  '/api/import-retry': typeof ApiImportRetryRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/import2'
    | '/import3'
    | '/library'
    | '/sign-in'
    | '/sign-up'
    | '/api/import'
    | '/api/import-retry'
    | '/reader/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/import2'
    | '/import3'
    | '/library'
    | '/sign-in'
    | '/sign-up'
    | '/api/import'
    | '/api/import-retry'
    | '/reader/$bookId'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/import2'
    | '/import3'
    | '/library'
    | '/sign-in'
    | '/sign-up'
    | '/api/import'
    | '/api/import-retry'
    | '/reader/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  Import2Route: typeof Import2Route
  Import3Route: typeof Import3Route
  LibraryRoute: typeof LibraryRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiImportRoute: typeof ApiImportRoute
  ApiImportRetryRoute: typeof ApiImportRetryRoute
  ReaderBookIdRoute: typeof ReaderBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import3': {
      id: '/import3'
      path: '/import3'
      fullPath: '/import3'
      preLoaderRoute: typeof Import3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import2': {
      id: '/import2'
      path: '/import2'
      fullPath: '/import2'
      preLoaderRoute: typeof Import2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$bookId': {
      id: '/reader/$bookId'
      path: '/reader/$bookId'
      fullPath: '/reader/$bookId'
      preLoaderRoute: typeof ReaderBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-retry': {
      id: '/api/import-retry'
      path: '/api/import-retry'
      fullPath: '/api/import-retry'
      preLoaderRoute: typeof ApiImportRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import': {
      id: '/api/import'
      path: '/api/import'
      fullPath: '/api/import'
      preLoaderRoute: typeof ApiImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  Import2Route: Import2Route,
  Import3Route: Import3Route,
  LibraryRoute: LibraryRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiImportRoute: ApiImportRoute,
  ApiImportRetryRoute: ApiImportRetryRoute,
  ReaderBookIdRoute: ReaderBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
